version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip3 install pylint yapf
      - run: sudo pip3 install -r requirements.txt
      - run: make lint


